### ISSUE TITLE
MP doesn't work on win machines

### ISSUE THREAD

**Issue by nesnoj** [rl-institut/simbev#29]
Workers do not get initialized or do not start, simbev only produces an empty dir.
Restructure main file to cover MP for linux+win.

**Comment by Mosc5** [comment]
The issue seems to be that windows does not use fork(). Any variable that was set under `if __name__ == '__main__'` is not accessible for each process in the pool. `main_simbev.py` needs to be restructured to account for this.

**Comment by Mosc5** [comment]
Restructuring the main script this way seems to have solved the problem!
