### ISSUE TITLE
Charging Capacity is sometimes not correct

### ISSUE THREAD

**Issue by khelfen** [rl-institut/simbev#31]
Sometimes the charging capacity is off by decimals. This is a problem when the parking time is equal to the minimum needed charging time. See the example below

![Clipboard - 13  Juli 2021 16_28](https://user-images.githubusercontent.com/46815982/125626974-f629cc69-1811-4829-8d41-b319c1994007.png)

The charging point efficiency was set to 1.0 in this run and the charging capacity should therefor be 3.7 and not 3.69

**Comment by nesnoj** [comment]
@timroepcke will check this
