### ISSUE TITLE
Integrate MiD seasonal data

### ISSUE THREAD

**Issue by nesnoj** [rl-institut/simbev#4]
For more trip realism and variability it would be great to have the MiD seasonal probability distributions integrated into the tool.

- [x] add data to repo -> @Mosc5 you already have this data, right? Could you please add it?
- [ ] use it in simBEV, maybe using a simple param in the config to select the season as a first very simple solution

**Comment by Mosc5** [comment]
I added the new data to the repo. The script that turns these into a time series isn't perfect yet (weeks always start on monday even if previous ones didnt end on sunday) but it should make the added data usable in simbev
