### ISSUE TITLE
Provide condensed output csv

### ISSUE THREAD

**Issue by Mosc5** [rl-institut/simbev#45]
The current outputs per car can be difficult to handle and provide a lot of information that isnt useful in all cases. For applications where only energy sums and use cases are relevant, there should be an option to receive a condensed output csv similar to the one in SpiceEV

csv concept:
time series for total charging power per use case
columns now: timestep, sum CS power, sum per trip destination
columns after refactoring: timestep, sum CS power, sum hpc, sum public, sum work, sum home

**Comment by Mosc5** [comment]
Things to consider before opening a PR:

- wait for #46 and change up output function to match new column names
- maybe add config option for output files

**Comment by nesnoj** [comment]
As there was no issue handling keyword in #49, I close this one manually.
