### ISSUE TITLE
Output data is confusing

### ISSUE THREAD

**Issue by Mosc5** [rl-institut/simbev#46]
Naming and actual values in the vehicle csvs tend to be unclear.

- charging_time currently looks at parking time with available charging station instead of actual time that the vehicle takes to charge

- netto_charging_capacity means the power that goes into the car, including any losses. maybe add grid side power as well to improve clarity

- declare units in the column name

- car type and capacity dont change, do they need to be in every row?

**Comment by nesnoj** [comment]
Do you intend to change this prior to the release?

**Comment by Mosc5** [comment]
This ties together with #45. I'm not sure if these are supposed to be part of the release, maybe @timroepcke can answer
