### ISSUE TITLE
Implementation of charging efficiency and losses

### ISSUE THREAD

**Issue by Mosc5** [rl-institut/simbev#47]
@timroepcke and I noticed that the calculation of actual charging power might be incorrect in it's current state.

To consider: How does eta get implemented? What is the actual charging power vs grid charging power, and which do we set in the config? Do we consider losses inside the car or just the charging station?

**Comment by nesnoj** [comment]
I guess you will fix this prior to the release?

**Comment by Mosc5** [comment]
This issue is high priority since a simulation using efficiency is required in one of our projects. Will be fixed as soon as we coordinate on how the charging power should be calculated

**Comment by timroepcke** [comment]
closed with #49
