### ISSUE TITLE
Hard-coded params in compile script

### ISSUE THREAD

**Issue by nesnoj** [rl-institut/simbev#51]
Please use generic solution for this:

https://github.com/rl-institut/simbev/blob/f7a61ad744c4993fdc2c12675657d0b8883cbb1e/simbev/helpers/helpers.py#L155-L158

Either by
- adding a proper argparse or
- deleting it and providing the 3 lines as little script example in the readme

**Comment by timroepcke** [comment]
code removed with PR52, new example script coming later
