### ISSUE TITLE
Missing EVs' CSVs in results

### ISSUE THREAD

**Issue by nesnoj** [rl-institut/simbev#54]
I did some runs over the holidays (with latest release) and came across another problem. With [this scenario](https://gist.github.com/nesnoj/3f5c3af004273a4ba4ab51e7174ad25b) the resulting number of EVs is too small (see sums at right of table):

| region_id | RegioStaR7 | bev_mini | bev_medium | bev_luxury | phev_mini | phev_medium | phev_luxury | EXPECTED SUM | ACTUAL SUM |
|---|---|---|---|---|---|---|---|---|---|
| 71 | SR_Metro | 1690 | 3844 | 1235 | 1047 | 2382 | 765 | 10963 | 1371 |
| 72 | SR_Gross | 1750 | 3676 | 1045 | 1084 | 2278 | 647 | 10480 | 10480 |
| 73 | SR_Mitte | 3548 | 7776 | 2421 | 2197 | 4818 | 1499 | 22259 | 8536 |
| 74 | SR_Klein | 880 | 1958 | 574 | 545 | 1213 | 355 | 5525 | 3290 |
| 75 | LR_Zentr | 816 | 1760 | 511 | 506 | 1090 | 317 | 5000 | 1173 |
| 76 | LR_Mitte | 2050 | 4625 | 1331 | 1269 | 2866 | 824 | 12965 | 6886 |
| 77 | LR_Klein | 2250 | 5230 | 1487 | 1394 | 3241 | 921 | 14523 | 980 |

- Except for region 72 / SR_Gross the number of generated CSVs is too small (total: 32716 instead of 81715).
- All EV types are affected
- CSVs for PHEVs are only generated for the region which shows correct numbers (72 / SR_Gross)
- I ran again with 1 week (`2011-01-01` to `2011-01-07`) with similar results:
  - now I get slightly more: 33271 EVs
  - here, the **number of EVs is correct for 74 and 76** (and like before PHEVs are created for those 2 regions with correct EV numbers)
- I observed a similar behaviour for the `default_RS7` scenario (total: 38251 instead of ~140k). Here, none of the regions show correct number of CSVs and there're no PHEVs at all.

This seems to be a general problem.
Any ideas, @timroepcke @Mosc5? Could this behaviour be related to the sampling?

**Comment by nesnoj** [comment]
Update:
- I ran all regions with 100 EVs per type an get 4200 CSVs as expected
- I ran all regions with 500 EVs per type an get **16899 CSVs** (thereof 7500 PHEVs) instead of 21000
- I ran all regions with 1000 EVs per type an get **30588 CSVs** (thereof 12000 PHEVs) instead of 42000

Can you make sense of this?

**Comment by Mosc5** [comment]
When running the rs7 defaut scenario in a single thread, I get the following error:

![grafik](https://user-images.githubusercontent.com/82523186/147938830-1b3d84f1-9837-400c-aee6-e9d56e203057.png)

Multithreading eats those kinds of errors and just continues with the next region, which explains why it hadn't been noticed before.
