### ISSUE TITLE
Information about maximum charging capacity of the charging point

### ISSUE THREAD

**Issue by khelfen** [rl-institut/simbev#58]
Some reactive power control strategies require information about the maximum charging capacity of the charging point because they depend on it. E.g. the cos phi (P) control sets the cos(phi) in dependence of the current `P` in proportion to the maximum `Pmax` (which is equivalent to the maximum charging capacity of the charging point).

At the moment this information is missing as the charging capacity given is the minimum of either the maximum charging capacity of the EV or the charging point.

**Comment by mosc5** [comment]
This got resolved with the new output format
